### ISSUE TITLE
number 'c' is followed by 'ci' and not 'd' when let g:bullets_renumber_on_change = 0

### ISSUE THREAD

**Issue by harshad1** [bullets-vim/bullets.vim#67]
I am using bullets in neovim. Installed with vim-plug. The only setting I have changed is `let g:bullets_renumber_on_change = 0`

If I have

```
a. foo
b. bar
c. baz <- <CR>
```

I expect the next number to be 'd'. However I get 'ci' (and then 'cii', 'ciii', 'civ' etc etc).

This also happens when block selecting and indenting:

```
1. foo
2. bar
3. baz
4. fee
5. fi
6. fo
7. fum
```
block selecting 2->6 and indenting gives me:

```
1. foo
    a. bar
    b. baz
    c. fee
    ci. fi
    cii. fo
7. fum
```

**Comment by dkarter** [comment]
@kaymmm could you please take a look at this? seems related to recent changes

**Comment by aodecipher** [comment]
This seems to be reltaed to the issue I raised a few days ago. https://github.com/dkarter/bullets.vim/issues/80#issue-631110531

**Comment by harshad1** [comment]
This issue appears to have been fixed. Not sure which change did it.

**Comment by arisolt** [comment]
Sorry but this issue is still happening. I'm on the latest version.

**Comment by arisolt** [comment]
It seems some letters in the ABC/abc numbering style are getting mistaken with the ROM/rom numbering style and this causes the numbering style to switch from ABC/abc to ROM/rom.

**Comment by arisolt** [comment]
can this issue please be reopened? I am still experiencing this bug.

**Comment by harshad1** [comment]
Sure. Could you post an example?

**Comment by arisolt** [comment]
Thank you. The example in OP reproduces the error.
